
production: false

url: "http://ajiro.fr"
baseurl: ""

markdown: kramdown

gems:
- jekyll-paginate
- jekyll-assets

exclude:
- README.md
- Gemfile.lock
- Gemlfile
- run
- quick-run

defaults:
- scope:
    path: articles
    type: posts
  values:
    permalink: /articles/:year/:month/:day/:title.html
    layout: article
- scope:
    path: books
    type: books
  values:
    layout: book
- scope:
    path: tales
    type: tales
  values:
    layout: tale
- scope:
    path: games
    type: games
  values:
    layout: game

collections:
  books:
    output: true
  tales:
    output: true
  games:
    output: true

version:
  #bootstrap: '3.3.7'
  bootstrap: '4.0.0-alpha.5'
  font_awesome: '4.7.0'
  jquery: '3.1.1'
