
production: false

url: "http://ajiro.fr"
baseurl: ""

markdown: kramdown

gems:
- jekyll-paginate
- jekyll-assets

exclude:
- README.md
- Gemfile

defaults:
- scope:
    path: "articles"
    type: "posts"
  values:
    permalink: /articles/:title.html
    layout: article
