
production: false

url: "http://ajiro.fr"
baseurl: ""

markdown: kramdown

gems:
- jekyll-paginate
- jekyll-assets

exclude:
- README.md
- Gemfile

defaults:
- scope:
    path: articles
    type: posts
  values:
    permalink: /articles/:year/:month/:day/:title.html
    layout: article
- scope:
    path: books
    type: books
  values:
    layout: book
- scope:
    path: tales
    type: tales
  values:
    layout: tale
- scope:
    path: games
    type: games
  values:
    layout: game
- scope:
    path: products
    type: products
  values:
    layout: products

collections:
  books:
    output: true
  tales:
    output: true
  games:
    output: true
  products:
    output: true
