defaultContentLanguage: "fr"
languageCode: fr-fr
title: Ajiro
copyright: "&copy; 2016, Ajiro"
baseurl: http://ajiro.fr/
theme: template-ajiro

enableEmoji: true
googleAnalytics: "UA-89122379-1"
metaDataFormat: yaml

taxonomies:
  author: authors
  category: categories
  tag: tags

params:
  version:
    bootstrap: 4.0.0-alpha.5
    font_awesome: 4.7.0
    jquery: 3.1.1

menu:
  right:
    - Name: "Articles"
      Pre: "<i class='fa fa-file-text-o'></i>"
      URL: /articles/
    - Name: "Talks"
      Pre: "<i class='fa fa-desktop'></i>"
      URL: /talks/
    - Name: "Livres"
      Pre: "<i class='fa fa-book'></i>"
      URL: /books/
    - Name: "RSS"
      Pre: "<i class='fa fa-rss'></i>"
      URL: /feed.all.xml
