languageCode: fr-fr
title: Ajiro
baseurl: http://ajiro.fr/
theme: template-ajiro

taxonomies:
  author: authors
  tag: tags

params:
  version:
    bootstrap: 4.0.0-alpha.5
    font_awesome: 4.7.0
    jquery: 3.1.1
