defaultContentLanguage: "fr"
languageCode: fr-fr
title: Ajiro
copyright: "&copy; 2016, Ajiro"
baseurl: http://ajiro.fr/
theme: template-ajiro

disableRSS: false
enableRobotsTXT: true
enableEmoji: true
googleAnalytics: "UA-89122379-1"
metaDataFormat: yaml
preserveTaxonomyNames: true

taxonomies:
  author: authors
  category: categories
  tag: tags

params:
  version:
    bootstrap: 4.0.0-alpha.5
    font_awesome: 4.7.0
    jquery: 3.1.1

menu:
  left:
    - Name: "Membres"
      Pre: "<i class='fa fa-users'></i>"
      URL: /members/
      Weight: 10
  right:
    - Name: "Articles"
      Pre: "<i class='fa fa-file-text-o'></i>"
      URL: /articles/
      Weight: 10
    - Name: "Talks"
      Pre: "<i class='fa fa-desktop'></i>"
      URL: /talks/
      Weight: 20
    - Name: "Livres"
      Pre: "<i class='fa fa-book'></i>"
      URL: /books/
      Weight: 30
    - Name: "RSS"
      Pre: "<i class='fa fa-rss'></i>"
      URL: /feed.all.xml
      Weight: 40

sitemap:
  changefreq: "weekly"
  filename: "sitemap.xml"
